## DataFrames

When you combine multiple Series together, it forms a Dataframe.

In [1]:
import numpy as np
import pandas as pd

### Creating a DataFrame

In [5]:
#Using Dictionary

data = {
    'Name': ['John', 'Peter', 'Mark'],
    'Age': [28, 42, 32],
    'City': ['NYC', 'LA', 'CAL'],
    'Salary': [45000, 55000, 85000]
}

df_dict = pd.DataFrame(data)

In [6]:
df_dict

    Name  Age City  Salary
0   John   28  NYC   45000
1  Peter   42   LA   55000
2   Mark   32  CAL   85000

In [12]:
#Using List

data_list = [
    ['John', 28, 'NYC', 65000],
    ['Peter', 26, 'LA', 75000],
    ['Mark', 45, 'CAL', 85000],
]

df_list = pd.DataFrame(data_list)

#Colums (headers)
cols = ['Name', 'Age', 'City', 'Salary']
df_list_col = pd.DataFrame(data_list, columns = cols)

In [7]:
df_list

       0   1    2      3
0   John  28  NYC  65000
1  Peter  26   LA  75000
2   Mark  45  CAL  85000

In [13]:
df_list_col

    Name  Age City  Salary
0   John   28  NYC   65000
1  Peter   26   LA   75000
2   Mark   45  CAL   85000

### Selection & Indexing of Columns

In [14]:
df_list_col

    Name  Age City  Salary
0   John   28  NYC   65000
1  Peter   26   LA   75000
2   Mark   45  CAL   85000

In [16]:
df_list_col['Name']

0     John
1    Peter
2     Mark
Name: Name, dtype: object

In [18]:
df_list_col['City']

0    NYC
1     LA
2    CAL
Name: City, dtype: object

In [19]:
#Multiple Cols at Once

df_list_col[['Name', 'Age']]

    Name  Age
0   John   28
1  Peter   26
2   Mark   45

### Creating a new column

In [20]:
df_list_col

    Name  Age City  Salary
0   John   28  NYC   65000
1  Peter   26   LA   75000
2   Mark   45  CAL   85000

In [39]:
df_list_col["Designation"] = ["Doctor", "Engg", "CA"]
df_list_col

    Name  Age Designation
0   John   28      Doctor
1  Peter   26        Engg
2   Mark   45          CA

### Removing Columns

In [ ]:
# doesn't permanantly removes cols / rows gives a copy of if deleted
df_list_col.drop("Designation", axis = 1)

    Name  Age City  Salary
0   John   28  NYC   65000
1  Peter   26   LA   75000
2   Mark   45  CAL   85000

In [ ]:
df_list_col #Designation not dropped

    Name  Age City  Salary Designation
0   John   28  NYC   65000      Doctor
1  Peter   26   LA   75000        Engg
2   Mark   45  CAL   85000          CA

In [ ]:
df_list_col.drop("Designation", axis = 1, inplace = True) #Permanantly Delete- (inplace = True)

In [29]:
df_list_col

    Name  Age City  Salary
0   John   28  NYC   65000
1  Peter   26   LA   75000
2   Mark   45  CAL   85000

In [ ]:
#Removing Multiple Colums

df_list_col.drop(["City", "Salary"], axis = 1, inplace = True)

In [31]:
df_list_col

    Name  Age
0   John   28
1  Peter   26
2   Mark   45

In [32]:
# Removing Rows -> (axis = 0)

df_list_col.drop(0, axis = 0)

    Name  Age
1  Peter   26
2   Mark   45

### Selecting Row

In [33]:
# loc (location) - for rows

df_list_col.loc[0]

Name    John
Age       28
Name: 0, dtype: object

In [35]:
df_list_col.loc[[0, 1]]

    Name  Age
0   John   28
1  Peter   26

In [37]:
# iloc (index location)

df_list_col.iloc[2]

Name    Mark
Age       45
Name: 2, dtype: object

### Selecting Subsets of Rows & Cols

In [41]:
df_list_col.loc[[0, 1]][["Age", "Designation"]]

   Age Designation
0   28      Doctor
1   26        Engg

In [43]:
df_list_col.loc[[1, 2]][["Name", "Age"]]

    Name  Age
1  Peter   26
2   Mark   45

### Conditional Selection

In [44]:
df_list_col

    Name  Age Designation
0   John   28      Doctor
1  Peter   26        Engg
2   Mark   45          CA

In [45]:
# People with Age > 26
df_list_col[df_list_col["Age"] > 26]

   Name  Age Designation
0  John   28      Doctor
2  Mark   45          CA

In [ ]:
#People with Age > 26 & Designation CA
df_list_col[(df_list_col["Age"] > 26) & (df_list_col["Designation"] == "CA")]

#for OR -> |

   Name  Age Designation
2  Mark   45          CA