## Missing Data

##### Empty Values in DataSet -> either fill them or remove them

In [10]:
import numpy as np
import pandas as pd

In [11]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

df = pd.DataFrame(data)

In [12]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

### Finding Missing/NULL Data

In [13]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [14]:
df.isna().sum() #for count of null values - col wise

A    1
B    0
C    2
D    3
dtype: int64

In [15]:
df.isna().any() #for checking if each col has null value or not

A     True
B    False
C     True
D     True
dtype: bool

### Removing Missing/NULL Data

In [16]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [17]:
# Removing rows containing NULL Value

df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
# thresh - threshold for non-null values - in rows

df.dropna(thresh = 3) #atleast 3 non-null values

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

### Filling the Missing Data

In [20]:
#Filling All Null Values with 0

df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [ ]:
#Filling each col with different values - col wise

vals = {
    'A': 0,
    'B': 100,
    'C': 300,
    'D': 500
}

df.fillna(value = vals)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  500.0
2  0.0  3    3.0  500.0
3  4.0  4  300.0  500.0
4  5.0  5  300.0    5.0

In [22]:
#Filling with mean

df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0